DZ skeleton
js-tasks-ru/htmlcss-20220919_khlopovdima pull request #10
Opened 2022-09-29 17:12 UTC by Dima163163

2022-09-29 17:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-30 02:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-01 07:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-01 10:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-02 19:54 UTC, GSemikozov requested changes

2022-10-02 19:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__line">
skeleton__lines

2022-10-02 19:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                    <div class="skeleton__line_small"></div>
class="skeleton__line skeleton__line_small"

2022-10-02 19:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line {
skeleton__lines

2022-10-02 19:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line_small {
```.skeleton__line {
height: 20px;
	background: linear-gradient(92.51deg, #DDE2E5 6.44%, #E2E6E8 38.47%, #F3F5F5 56.48%, #E3E7EA 77.5%, #DDE2E5 102.52%);
}```
остальное - в модификаторы

2022-10-02 19:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line_small {
причем - марджины все-таки лучше иным образом привязать

2022-10-02 19:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line_small {
например через родителя

2022-10-05 06:13 UTC, GSemikozov requested changes

2022-10-05 06:13 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +	margin-top: 8px;
в модификаторе мы меняет только ширину, другие свойства не надо дублировать, и марджины лучше все-таки через родителя проставлять и через gap

2022-10-05 06:13 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +	margin-top: 8px;
width: 100%
про марджины - см выше

2022-10-06 08:48 UTC, GSemikozov approved these changes

2022-10-06 08:48 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-10-06 08:51 UTC, GSemikozov approved these changes

2022-10-06 08:51 UTC, merged