DZ calendar
js-tasks-ru/htmlcss-20220919_khlopovdima pull request #13
Opened 2022-10-01 12:49 UTC by Dima163163

2022-10-01 12:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-02 20:06 UTC, GSemikozov requested changes

2022-10-02 20:06 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item:nth-child(29),
без nth-child, просто через модификаторы

2022-10-02 20:06 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item:nth-child(30),
и тут

2022-10-02 20:06 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +	color: #90A0B7;
тут видимо еще и отступ снизу дополнительный нужен

2022-10-05 06:13 UTC, GSemikozov approved these changes

2022-10-05 06:21 UTC, merged