DZ page-layout
js-tasks-ru/htmlcss-20220919_khlopovdima pull request #28
Opened 2022-10-16 14:28 UTC by Dima163163

2022-10-16 14:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-17 10:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-17 10:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-17 13:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-17 13:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-18 19:46 UTC, GSemikozov requested changes

2022-10-18 19:46 UTC, GSemikozov commented on components/component-sectioin/component-section.css
> +.component-sectioin__top {
а для чего фиксируем высоту у этих элементов?

2022-10-18 19:46 UTC, GSemikozov commented on components/pages-toggle/pages-toggle.css
> +.navbar__toggle {
navbar в блоке .toggle? лишнее, удалим

2022-10-18 19:46 UTC, GSemikozov commented on pages/template.css
>  body,
отсюда и ниже - получается что в этом файле мы описываем всякие разные стили. Так делать не надо - страницу темплейта мы тоже собираем из блоков, подобно тому как собирали Главную

2022-10-20 07:48 UTC, GSemikozov requested changes

2022-10-20 07:48 UTC, GSemikozov commented on pages/template.css
> +.component-section__top {
лишнее, удалим

2022-10-20 08:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-20 08:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-20 08:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-20 10:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-20 10:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-20 11:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-20 11:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-20 11:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-23 17:31 UTC, GSemikozov approved these changes

2022-10-23 17:31 UTC, merged